In [183]:
# Cellule 1 : Imports et configuration
%load_ext autoreload
%autoreload 2

import pandas as pd

# Import du processeur de production spécialisé
from tools.OI_class_OP import OI_ProductionProcessor
from tools.OI_Dashboard import ProductionDashboard
from tools.OI_Dashboard_v2 import AjouterVisualisationsAvancees


# Configuration de l'affichage pour voir toutes les colonnes
pd.set_option('display.max_columns', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [184]:
# Cellule 2 : Définition des métadonnées de tags API
tags = [
    {'tag':'WQ33222VA', 'nom':'ester_cons','info':'Totalisation du Peson Acetate/Propionate', 'agg': 'FIRST' },
    {'tag':'NOP_ESTERS', 'nom':'ester_nop','info':"Nombres des opérations d'esters",'agg':'FIRST' },
    {'tag':'3340_type', 'nom':'A/P','info':'Acetate ou Propionate','agg':'FIRST' },
    {'tag':'CTY_ACV43A_Teneur Vit. A (UV)', 'nom':'Acetate_UV','info':'ACV43A teneur en acetate', 'agg': 'MEAN'},
    {'tag':'CTY_A3340FGB_Teneur arr. Vit. A (UV)', 'nom':'Propionate_UV', 'info':'A3340FGB teneur en propionate', 'agg': 'MEAN'},
    {'tag':'PU3310VA_Sign','nom':'PU3310','info':'signature du PU3310','agg':'FIRST'},
    {'tag':'PU3320VA_Sign','nom':'PU3320','info':'signature du PU3320','agg':'FIRST'},
    {'tag':'PU3340VA_Sign','nom':'PU3340','info':'signature du PU3340','agg':'FIRST'},
    {'tag':'FQ32202VA_UV','nom':'Hexane','info':'VA diluée dans de l\'hexane', 'agg': 'FIRST'},
    {'tag':'CTY_A3230A_Teneur en rétinol', 'nom':'Retinol_UV','info':'A3230A teneur en rétinol lavé', 'agg': 'MEAN'},
    {'tag':'LI33203VA','nom':'R33020','info':'niveau du R33020', 'agg': 'FIRST'},
    {'tag':'LI33218VA','nom':'R33022','info':'niveau du R33022', 'agg': 'FIRST'},
    {'tag':'LI33225VA','nom':'R33061','info':'niveau du R33061', 'agg': 'FIRST'},
    {'tag':'WI33222VA','nom':'R33060','info':'peson du R33060', 'agg': 'FIRST'},
    {'tag':'FQ32202VA','nom':'retinol_cons','info':'peson du R33060', 'agg': 'FIRST'},
    {'tag':'LI32209VA','nom':'R32031','info':'niveau du R32031', 'agg': 'FIRST'},
]

In [185]:
# Cellule 3 : Variable Produits unifiée (Acetate & Propionate)
# Plus aucune distinction batch / continu pour le calcul global du stock d'un produit.
produits = [
    {
        'nom': 'Ester',
        'conso': {
            'value': 'ester_cons',
            'scale': 1e-9,
            'type':'A/P',
            'uv': ['Acetate_UV', 'Propionate_UV'],
        },
        'CMJ': 9.5,
        'NOP': {
            'value':'NOP_ESTERS',
            'scale': 1,
            'type': None,
        },
        'stock': [
            # Batchs
            {'pu': 'PU3310', 'in': 540, 'out': 710, 'value': 'Hexane', 'uv': 'Retinol_UV', 'scale': 1/(825 * 100.)},
            {'pu': 'PU3310', 'in': 710, 'out': 2320, 'value': None, 'uv': None, 'scale': 2.71},
            {'pu': 'PU3320', 'in': 430, 'out': 2020, 'value': None, 'uv': None, 'scale': 2.71},
            # Continus
            {'pu': None, 'value': 'R33020', 'min': 14, 'epalage': [[28.62, 21.22, 3.866, -0.0983], [-228.84, 74.557]], 'uv': 'Retinol_UV', 'scale': 1/100., 'cond':'A/P', 'val_cond':[1/344,1/359]},
            {'pu': None, 'value': 'R33022', 'min': 14, 'epalage': [[6.25, 5.4525, 0.898, -0.0256], [-35, 97, 16.039]], 'uv': 'Retinol_UV', 'scale': 1/100., 'cond':'A/P', 'val_cond':[1/344,1/359]},
            {'pu': None, 'value': 'R33061', 'min': 18, 'epalage': [[0.69, 0.72, 0.296, -0.0059], [-30.03, 5.836]], 'uv': None, 'scale': 0.95 , 'cond':'A/P', 'val_cond':[1/344,1/359]},
            {'pu': 'PU3340', 'in': 0, 'out': 710, 'value': 'R33060', 'uv': None, 'scale': 0.95, 'cond': 'A/P', 'val_cond': [1/344, 1/359]}
        ]
    },
    {
        'nom': 'Retinol',
        'conso': {
            'value':'retinol_cons',
            'scale': 1e-5, # Ajustement de l'échelle pour le retinol g et analyse en %
            'uv': ['Retinol_UV','Retinol_UV'],
        },
        'CMJ': 1,
        'stock': [
            # Batchs
            {'pu': None, 'value': 'R32031', 'uv': 'Retinol_UV', 'scale': 1/(825 * 100.)},
        ]
    }
]

In [186]:
# Cellule 4 : Initialisation du processeur de production spécialisé
processor = OI_ProductionProcessor(
    url_base = 'https://oianalytics-100.optimistik.fr/api/oianalytics/time-values/query?',
    start = '2026-01-01',
    end = '2026-12-31',
    tags_metadata = tags,
    produits = produits,
    interval = 'PT15M',
    verbose = False
)

In [187]:
(processor.agg_mapping)

{'WQ33222VA': 'FIRST',
 'NOP_ESTERS': 'FIRST',
 '3340_type': 'FIRST',
 'CTY_ACV43A_Teneur Vit. A (UV)': 'MEAN',
 'CTY_A3340FGB_Teneur arr. Vit. A (UV)': 'MEAN',
 'PU3310VA_Sign': 'FIRST',
 'PU3320VA_Sign': 'FIRST',
 'PU3340VA_Sign': 'FIRST',
 'FQ32202VA_UV': 'FIRST',
 'CTY_A3230A_Teneur en rétinol': 'MEAN',
 'LI33203VA': 'FIRST',
 'LI33218VA': 'FIRST',
 'LI33225VA': 'FIRST',
 'WI33222VA': 'FIRST',
 'FQ32202VA': 'FIRST',
 'LI32209VA': 'FIRST'}

In [188]:
# Cellule 5 : Téléchargement et calcul automatique des bilans par produit
processor.merge()
processor.compute_production_balance()

# Visualisation des premières lignes calculées
processor.data.describe()

,ester_cons,ester_nop,A/P,Acetate_UV,Propionate_UV,PU3310,PU3320,PU3340,Hexane,Retinol_UV,R33020,R33022,R33061,R33060,retinol_cons,R32031,consommation_Ester,stock_Ester_tmp_PU3310_Hexane_0,stock_Ester_tmp_PU3310_None_1,stock_Ester_tmp_PU3320_None_2,stock_Ester_tmp_None_R33020_3,stock_Ester_tmp_None_R33022_4,stock_Ester_tmp_None_R33061_5,stock_Ester_tmp_PU3340_R33060_6,stock_Ester,consommation_Retinol,stock_Retinol_tmp_None_R32031_0,stock_Retinol,conso_delta_Ester,delta_stock_Ester,production_Ester,conso_delta_Retinol,delta_stock_Retinol,production_Retinol
count,1.759800e+04,17598.000000,17598.000000,1.759800e+04,1.759800e+04,17589.000000,17591.000000,17591.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,1.759800e+04,17598.000000,17598.000000,17598.000000,17598.000000,17598.000000,1.759800e+04,17598.000000,1.759800e+04
mean,2.506412e+06,2007.322910,0.062957,2.226411e+06,2.265030e+06,1033.950765,959.692854,460.541186,2609.035421,20.747532,46.326775,5.214689,7.465271,694.773531,490254.314329,48.064659,636.072816,0.029819,1.422604,1.591998,1.940225,0.035470,0.078884,1.435923,6.534923,5.522793e+05,0.012085,0.012085,636.072816,0.948635,637.021451,5.522793e+05,0.000530,5.522793e+05
std,1.795161e+05,147.039691,0.242851,3.591763e+04,5.846116e+04,616.435514,552.485508,118.917576,1877.930864,0.351151,20.332392,2.508741,11.493508,348.676147,284566.795327,21.039715,402.063794,0.145300,1.353351,1.334151,0.909586,0.016835,0.168152,0.946077,2.120610,5.948545e+05,0.005291,0.005291,402.063794,2.120610,402.578559,5.948545e+05,0.005291,5.948545e+05
min,2.221310e+06,1774.000000,0.000000,2.078915e+06,2.188000e+06,100.000000,100.000000,100.000000,0.000000,20.000000,-8.142390,-0.695313,-0.418438,4.689820,640.456000,-1.303840,0.000000,0.000000,0.000000,0.000000,0.000805,0.001665,0.001218,0.000000,0.707269,0.000000e+00,-0.000329,-0.000329,0.000000,-4.879019,-1.628659,0.000000e+00,-0.011884,0.000000e+00
25%,2.338260e+06,1870.000000,0.000000,2.221983e+06,2.242000e+06,400.000000,400.000000,410.000000,0.000000,20.500000,24.695100,3.951400,2.342940,444.757750,245916.000000,39.850475,257.806890,0.000000,0.000000,0.000000,0.970678,0.024106,0.010825,0.739529,5.433274,8.278726e+01,0.009993,0.009993,257.806890,-0.153013,260.370914,8.278726e+01,-0.001562,8.278727e+01
50%,2.491690e+06,1997.000000,0.000000,2.231549e+06,2.242000e+06,1310.000000,1110.000000,410.000000,3954.680000,20.700000,46.212150,6.078130,3.265100,683.127500,469514.000000,45.121150,602.667376,0.000000,2.710000,2.710000,1.927900,0.040210,0.016519,1.512281,6.827207,1.883241e+02,0.011517,0.011517,602.667376,1.240919,603.560812,1.883241e+02,-0.000038,1.883234e+02
75%,2.662290e+06,2134.000000,0.000000,2.242726e+06,2.314000e+06,1310.000000,1530.000000,410.000000,4041.380000,21.200000,65.061200,6.761720,4.592383,950.487500,748072.000000,67.148400,985.358405,0.000000,2.710000,2.710000,2.777680,0.046003,0.026631,2.201559,7.978597,9.992177e+05,0.016835,0.016835,985.358405,2.392310,988.018333,9.992177e+05,0.005280,9.992177e+05
max,2.828610e+06,2270.000000,1.000000,2.325113e+06,2.626000e+06,2340.000000,2250.000000,810.000000,4836.070000,21.200000,91.590400,12.284600,73.884600,1323.150000,999821.000000,79.734400,1357.758686,1.207552,2.710000,2.710000,3.933059,0.099400,1.107856,3.590475,12.323393,1.997307e+06,0.019909,0.019909,1357.758686,6.737105,1359.551917,1.997307e+06,0.008354,1.997307e+06

In [189]:
# ✨ INITIALISER LE DASHBOARD ✨
dashboard = ProductionDashboard(processor)
AjouterVisualisationsAvancees(dashboard) 

print("\n✓ Dashboard prêt pour utilisation!")
#dashboard.resume_complet()

✓ Dashboard initialisé
  Produits: Ester, Retinol
  Période: 2026-01-01 → 2026-07-03
✅ Visualisations avancées ajoutées au dashboard!

   Nouvelles méthodes disponibles:
   • dashboard.plot_histogramme_tous_produits(mois=3)
   • dashboard.plot_waterfall_mois(mois=3)
   • dashboard.plot_histogramme_jours_mois_v1(mois=3, nom_produit='Ester')
   • dashboard.plot_histogramme_jours_mois_v2(mois=3, nom_produit='Ester')


✓ Dashboard prêt pour utilisation!

In [190]:
# Voir l'évolution temporelle d'un produit
dashboard.afficher_bilan_produit('Ester')

In [191]:
dashboard.plot_histogramme_jours_mois_v2(mois=7, annea=2026, nom_produit='Ester', std=2)

____________________________________________________________
BILAN JOURNALIER - 01 JUILLET 2026 (Terminé)
Période : du 01/07/2026 à 02:00 au 02/07/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7805
  Variation de Stock     : -0.3337
  Stock Entrée.          : -0.3350
  Stock Sortie.          : -0.6687
  Production             : 2.4468
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8191
  Variation de Stock     : -0.0068
  Stock Entrée.          : -0.0005
  Stock Sortie.          : -0.0073
  Production             : 0.8122
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 02 JUILLET 2026 (Terminé)
Période : du 02/07/2026 à 02:00 au 03/07/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.5450
  Variation de Stock     : 2.3726
  Stock Entrée.          : -0.6687
  Stock Sortie.          : 1.7039
  Production             : 7.9176
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.4689
  Variation de Stock     : 0.0070
  Stock Entrée.          : -0.0073
  Stock Sortie.          : -0.0004
  Production             : 2.4759
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 03 JUILLET 2026 (À date (En cours))
Période : du 03/07/2026 à 02:00 au 03/07/2026 à 15:45
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7505
  Variation de Stock     : -0.0634
  Stock Entrée.          : 1.7039
  Stock Sortie.          : 1.6404
  Production             : 2.6871
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8323
  Variation de Stock     : -0.0027
  Stock Entrée.          : -0.0004
  Stock Sortie.          : -0.0031
  Production             : 0.8296
____________________________________________________________
____________________________________________________________
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.
Erreur : Pas de données après le début de la période.

==========================================================================================
  📊 STATISTIQUES - PRODUCTION ESTER PAR JOUR - JULY 2026
==========================================================================================
Nombre de jours complets:           3
Production moyenne:                 4.35
Production min/max:                 2.45 / 7.92
Écart-type:                         2.52
Coefficient de variation:           58.0%
Production totale mois:             13.05
TRS mois: (jours complets)          4.35
Jours au-dessus de la moyenne:      1 / 3

🎯 RATIO oee (Production / CMJ en %):
  CMJ (Cible Journalière):            9.50
  oee Moyen (par jour):               45.8%
  oee Min/Max (par jour):             25.8% / 83.3%
  oee Cumulé à date:                  45.8%
  Jours > 100%:                       0 / 3

  Détail oee par jour:
    J01:   25.8% ❌
    J02:   83.3% ⚠️
    J03:   28.3% ❌
==========================================================================================

In [192]:
debut = '06-01-2026 02:00:00'
fin = '06-02-2026 02:00:00'
NOP = processor.data.loc[[fin],['ester_nop']].values[0] - processor.data.loc[[debut],['ester_nop']].values[0]
print('Ester NOP   : ', NOP, NOP * 2.71)
print('Ester peson : ',processor.data.loc[[fin],['ester_cons']].values[0] - processor.data.loc[[debut],['ester_cons']].values[0] )
print('Ester titre : ',processor.data.loc[[fin],['consommation_Ester']].values[0] - processor.data.loc[[debut],['consommation_Ester']].values[0])
print('Ester Stock : ',processor.data.loc[[fin],['stock_Ester']].values[0], processor.data.loc[[debut],['stock_Ester']].values[0] )
print('Ester Delta : ',processor.data.loc[[fin],['stock_Ester']].values[0] - processor.data.loc[[debut],['stock_Ester']].values[0])
print('Ester conso : ',processor.data.loc[[fin],['conso_delta_Ester']].values[0]- processor.data.loc[[debut],['conso_delta_Ester']].values[0] )
print('Ester prod  : ',processor.data.loc[[fin],['production_Ester']].values[0]- processor.data.loc[[debut],['production_Ester']].values[0] )
processor.data[debut:fin]

Ester NOP   :  [4.] [10.84]
Ester peson :  [3740.]
Ester titre :  [8.3173024]
Ester Stock :  [7.76989323] [5.29724975]
Ester Delta :  [2.47264348]
Ester conso :  [8.3173024]
Ester prod  :  [10.78994588]

,ester_cons,ester_nop,A/P,Acetate_UV,Propionate_UV,PU3310,PU3320,PU3340,Hexane,Retinol_UV,R33020,R33022,R33061,R33060,retinol_cons,R32031,consommation_Ester,stock_Ester_tmp_PU3310_Hexane_0,stock_Ester_tmp_PU3310_None_1,stock_Ester_tmp_PU3320_None_2,stock_Ester_tmp_None_R33020_3,stock_Ester_tmp_None_R33022_4,stock_Ester_tmp_None_R33061_5,stock_Ester_tmp_PU3340_R33060_6,stock_Ester,consommation_Retinol,stock_Retinol_tmp_None_R32031_0,stock_Retinol,conso_delta_Ester,delta_stock_Ester,production_Ester,conso_delta_Retinol,delta_stock_Retinol,production_Retinol
timestamp,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2026-06-01 02:00:00+00:00,2710770.0,2175.00,0.0,2231260.0,2188000.0,400.0,1120.0,710.0,0.00,20.6,57.9978,6.94141,10.02970,1256.3900,717187.0,44.5753,1095.154465,0.0,0.00,2.71,2.452419,0.047191,0.087640,0.000000,5.297250,999249.829855,0.011130,0.011130,1095.154465,-0.289038,1094.865427,999249.829855,-0.000425,999249.829430
2026-06-01 02:15:00+00:00,2710770.0,2175.00,0.0,2231260.0,2188000.0,400.0,1120.0,710.0,0.00,20.6,57.2839,6.91016,15.94610,1252.7800,717187.0,44.8255,1095.154465,0.0,0.00,2.71,2.420545,0.046925,0.175403,0.000000,5.352874,999249.829855,0.011193,0.011193,1095.154465,-0.233414,1094.921051,999249.829855,-0.000362,999249.829493
2026-06-01 02:30:00+00:00,2710770.0,2175.00,0.0,2231260.0,2188000.0,400.0,1135.0,810.0,0.00,20.6,55.6637,6.91016,22.43230,1251.0400,717187.0,72.0132,1095.154465,0.0,0.00,2.71,2.348207,0.046925,0.278607,0.000000,5.383739,999249.829855,0.017981,0.017981,1095.154465,-0.202548,1094.951917,999249.829855,0.006426,999249.836282
2026-06-01 02:45:00+00:00,2710770.0,2175.92,0.0,2231260.0,2188000.0,400.0,1200.0,410.0,0.00,20.6,53.4612,6.87500,29.39710,36.5625,717187.0,70.5189,1095.154465,0.0,0.00,2.71,2.249871,0.046626,0.390857,0.100972,5.498327,999249.829855,0.017608,0.017608,1095.154465,-0.087960,1095.066505,999249.829855,0.006053,999249.835908
2026-06-01 03:00:00+00:00,2710770.0,2176.00,0.0,2231260.0,2188000.0,400.0,1110.0,410.0,0.00,20.6,51.1893,6.87500,3.64990,214.3000,717187.0,71.4949,1095.154465,0.0,0.00,2.71,2.148437,0.046626,0.019260,0.591817,5.516140,999249.829855,0.017852,0.017852,1095.154465,-0.070147,1095.084318,999249.829855,0.006297,999249.836152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-02 01:00:00+00:00,2714510.0,2178.00,0.0,2220216.0,2188000.0,1310.0,1610.0,810.0,3975.14,20.6,45.8798,3.36135,22.32030,348.8450,733647.0,17.8650,1103.471767,0.0,2.71,2.71,1.911381,0.020212,0.276801,0.000000,7.628394,999253.220615,0.004461,0.004461,1103.471767,2.042107,1105.513874,999253.220615,-0.007094,999253.213521
2026-06-02 01:15:00+00:00,2714510.0,2179.00,0.0,2220216.0,2188000.0,1310.0,1620.0,410.0,3975.14,20.6,43.5132,3.25881,3.34044,167.6370,733647.0,16.5130,1103.471767,0.0,2.71,2.71,1.805718,0.019564,0.017062,0.462951,7.725294,999253.220615,0.004123,0.004123,1103.471767,2.139007,1105.610774,999253.220615,-0.007432,999253.213183
2026-06-02 01:30:00+00:00,2714510.0,2179.00,0.0,2220216.0,2188000.0,1310.0,1620.0,410.0,3975.14,20.6,40.5426,3.18842,3.91220,216.4220,733647.0,57.9776,1103.471767,0.0,2.71,2.71,1.673088,0.019123,0.021220,0.597677,7.731108,999253.220615,0.014477,0.014477,1103.471767,2.144821,1105.616588,999253.220615,0.002922,999253.223537
2026-06-02 01:45:00+00:00,2714510.0,2179.00,0.0,2220216.0,2188000.0,1310.0,1610.0,410.0,3975.14,20.6,38.4010,3.12014,3.90333,259.7660,733647.0,65.9208,1103.471767,0.0,2.71,2.71,1.577471,0.018700,0.021152,0.717377,7.754700,999253.220615,0.016460,0.016460,1103.471767,2.168413,1105.640180,999253.220615,0.004905,999253.225520
2026-06-02 02:00:00+00:00,2714510.0,2179.00,0.0,2220216.0,2188000.0,1310.0,1620.0,410.0,3975.14,20.6,36.0528,2.98154,3.99680,303.2780,733647.0,67.2773,1103.471767,0.0,2.71,2.71,1.472630,0.017852,0.021871,0.837541,7.769893,999253.220615,0.016799,0.016799,1103.471767,2.183606,1105.655373,999253.220615,0.005244,999253.225859

In [193]:
processor.calcul_cumul_journalier(1,6,2026,"Ester")

____________________________________________________________
BILAN JOURNALIER - 01 JUIN 2026 (Terminé)
Période : du 01/06/2026 à 02:00 au 02/06/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.3173
  Variation de Stock     : 2.4726
  Stock Entrée.          : -0.2890
  Stock Sortie.          : 2.1836
  Production             : 10.7899
____________________________________________________________
____________________________________________________________

{'Ester': {'consommation': 8.317302400000017,
  'delta_stock': 2.472643477741661,
  'production': 10.78994587774173}}

In [194]:
dashboard.afficher_bilan_journalier(jour=1, mois=7, annee=2026)

____________________________________________________________
BILAN JOURNALIER - 01 JUILLET 2026 (Terminé)
Période : du 01/07/2026 à 02:00 au 02/07/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7805
  Variation de Stock     : -0.3337
  Stock Entrée.          : -0.3350
  Stock Sortie.          : -0.6687
  Production             : 2.4468
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8191
  Variation de Stock     : -0.0068
  Stock Entrée.          : -0.0005
  Stock Sortie.          : -0.0073
  Production             : 0.8122
____________________________________________________________
____________________________________________________________

In [195]:
dashboard.plot_histogramme_annuee(annea=2026, nom_produit='Ester')

____________________________________________________________
BILAN JOURNALIER - 01 JANVIER 2026 (Terminé)
Période : du 01/01/2026 à 02:00 au 02/01/2026 à 01:30
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2673
  Variation de Stock     : -4.1001
  Stock Entrée.          : 3.0225
  Stock Sortie.          : -1.0776
  Production             : 4.1672
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5713
  Variation de Stock     : -0.0014
  Stock Entrée.          : 0.0015
  Stock Sortie.          : 0.0001
  Production             : 2.5700
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 02 JANVIER 2026 (Terminé)
Période : du 02/01/2026 à 02:15 au 03/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2920
  Variation de Stock     : -2.3258
  Stock Entrée.          : 2.9613
  Stock Sortie.          : 0.6355
  Production             : 5.9662
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7174
  Variation de Stock     : -0.0002
  Stock Entrée.          : 0.0001
  Stock Sortie.          : -0.0001
  Production             : 1.7172
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 03 JANVIER 2026 (Terminé)
Période : du 03/01/2026 à 02:00 au 04/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2965
  Variation de Stock     : -0.1118
  Stock Entrée.          : 0.6355
  Stock Sortie.          : 0.5237
  Production             : 8.1846
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5925
  Variation de Stock     : 0.0040
  Stock Entrée.          : -0.0001
  Stock Sortie.          : 0.0039
  Production             : 2.5966
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 04 JANVIER 2026 (Terminé)
Période : du 04/01/2026 à 02:00 au 05/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4864
  Variation de Stock     : -2.5205
  Stock Entrée.          : 0.5237
  Stock Sortie.          : -1.9969
  Production             : 2.9658
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6091
  Variation de Stock     : -0.0038
  Stock Entrée.          : 0.0039
  Stock Sortie.          : 0.0000
  Production             : 2.6052
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 05 JANVIER 2026 (Terminé)
Période : du 05/01/2026 à 02:00 au 06/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1836
  Variation de Stock     : 3.1964
  Stock Entrée.          : -1.9969
  Stock Sortie.          : 1.1995
  Production             : 11.3800
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7774
  Variation de Stock     : 0.0059
  Stock Entrée.          : 0.0000
  Stock Sortie.          : 0.0059
  Production             : 1.7833
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 06 JANVIER 2026 (Terminé)
Période : du 06/01/2026 à 02:00 au 07/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1141
  Variation de Stock     : 0.0033
  Stock Entrée.          : 1.1995
  Stock Sortie.          : 1.2029
  Production             : 8.1175
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6241
  Variation de Stock     : -0.0058
  Stock Entrée.          : 0.0059
  Stock Sortie.          : 0.0002
  Production             : 2.6184
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 07 JANVIER 2026 (Terminé)
Période : du 07/01/2026 à 02:00 au 08/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4959
  Variation de Stock     : 2.8446
  Stock Entrée.          : 1.2029
  Stock Sortie.          : 4.0475
  Production             : 8.3405
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5645
  Variation de Stock     : -0.0058
  Stock Entrée.          : 0.0002
  Stock Sortie.          : -0.0057
  Production             : 2.5587
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 08 JANVIER 2026 (Terminé)
Période : du 08/01/2026 à 02:00 au 09/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2796
  Variation de Stock     : -0.0404
  Stock Entrée.          : 4.0475
  Stock Sortie.          : 4.0070
  Production             : 8.2392
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5061
  Variation de Stock     : 0.0053
  Stock Entrée.          : -0.0057
  Stock Sortie.          : -0.0004
  Production             : 2.5114
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 09 JANVIER 2026 (Terminé)
Période : du 09/01/2026 à 02:00 au 10/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2916
  Variation de Stock     : -8.4586
  Stock Entrée.          : 4.0070
  Stock Sortie.          : -4.4516
  Production             : -0.1671
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : -0.0049
  Stock Entrée.          : -0.0004
  Stock Sortie.          : -0.0052
  Production             : -0.0049
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 10 JANVIER 2026 (Terminé)
Période : du 10/01/2026 à 02:00 au 11/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7454
  Variation de Stock     : 2.5854
  Stock Entrée.          : -4.4516
  Stock Sortie.          : -1.8662
  Production             : 5.3308
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.6589
  Variation de Stock     : 0.0009
  Stock Entrée.          : -0.0052
  Stock Sortie.          : -0.0044
  Production             : 1.6597
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 11 JANVIER 2026 (Terminé)
Période : du 11/01/2026 à 02:00 au 12/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4907
  Variation de Stock     : 3.2070
  Stock Entrée.          : -1.8662
  Stock Sortie.          : 1.3408
  Production             : 8.6978
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5229
  Variation de Stock     : -0.0035
  Stock Entrée.          : -0.0044
  Stock Sortie.          : -0.0079
  Production             : 2.5194
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 12 JANVIER 2026 (Terminé)
Période : du 12/01/2026 à 02:00 au 13/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2355
  Variation de Stock     : 0.1887
  Stock Entrée.          : 1.3408
  Stock Sortie.          : 1.5295
  Production             : 8.4242
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5168
  Variation de Stock     : 0.0143
  Stock Entrée.          : -0.0079
  Stock Sortie.          : 0.0064
  Production             : 2.5311
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 13 JANVIER 2026 (Terminé)
Période : du 13/01/2026 à 02:00 au 14/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.3149
  Variation de Stock     : -2.8835
  Stock Entrée.          : 1.5295
  Stock Sortie.          : -1.3539
  Production             : 5.4314
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.6902
  Variation de Stock     : -0.0013
  Stock Entrée.          : 0.0064
  Stock Sortie.          : 0.0051
  Production             : 1.6889
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 14 JANVIER 2026 (Terminé)
Période : du 14/01/2026 à 02:00 au 15/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.5387
  Variation de Stock     : -2.7158
  Stock Entrée.          : -1.3539
  Stock Sortie.          : -4.0697
  Production             : 2.8229
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8411
  Variation de Stock     : -0.0034
  Stock Entrée.          : 0.0051
  Stock Sortie.          : 0.0016
  Production             : 0.8377
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 15 JANVIER 2026 (Terminé)
Période : du 15/01/2026 à 02:00 au 16/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7805
  Variation de Stock     : 0.0817
  Stock Entrée.          : -4.0697
  Stock Sortie.          : -3.9880
  Production             : 2.8622
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8401
  Variation de Stock     : -0.0131
  Stock Entrée.          : 0.0016
  Stock Sortie.          : -0.0115
  Production             : 0.8270
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 16 JANVIER 2026 (Terminé)
Période : du 16/01/2026 à 02:00 au 17/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : 3.2430
  Stock Entrée.          : -3.9880
  Stock Sortie.          : -0.7451
  Production             : 3.2430
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8803
  Variation de Stock     : 0.0000
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0115
  Production             : 0.8803
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 17 JANVIER 2026 (Terminé)
Période : du 17/01/2026 à 02:00 au 18/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7582
  Variation de Stock     : -2.8270
  Stock Entrée.          : -0.7451
  Stock Sortie.          : -3.5720
  Production             : -0.0688
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : -0.0000
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0115
  Production             : -0.0000
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 18 JANVIER 2026 (Terminé)
Période : du 18/01/2026 à 02:00 au 19/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : 2.6825
  Stock Entrée.          : -3.5720
  Stock Sortie.          : -0.8896
  Production             : 2.6825
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.7642
  Variation de Stock     : 0.0082
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0033
  Production             : 0.7725
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 19 JANVIER 2026 (Terminé)
Période : du 19/01/2026 à 02:00 au 20/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.5609
  Variation de Stock     : 2.4241
  Stock Entrée.          : -0.8896
  Stock Sortie.          : 1.5345
  Production             : 7.9850
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.4981
  Variation de Stock     : 0.0085
  Stock Entrée.          : -0.0033
  Stock Sortie.          : 0.0052
  Production             : 2.5066
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 20 JANVIER 2026 (Terminé)
Période : du 20/01/2026 à 02:00 au 21/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.3286
  Variation de Stock     : 0.2556
  Stock Entrée.          : 1.5345
  Stock Sortie.          : 1.7901
  Production             : 8.5841
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5387
  Variation de Stock     : -0.0044
  Stock Entrée.          : 0.0052
  Stock Sortie.          : 0.0008
  Production             : 2.5343
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 21 JANVIER 2026 (Terminé)
Période : du 21/01/2026 à 02:00 au 22/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.4193
  Variation de Stock     : -2.6049
  Stock Entrée.          : 1.7901
  Stock Sortie.          : -0.8148
  Production             : 5.8144
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7187
  Variation de Stock     : -0.0007
  Stock Entrée.          : 0.0008
  Stock Sortie.          : 0.0001
  Production             : 1.7180
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 22 JANVIER 2026 (Terminé)
Période : du 22/01/2026 à 02:00 au 23/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1157
  Variation de Stock     : 0.2284
  Stock Entrée.          : -0.8148
  Stock Sortie.          : -0.5865
  Production             : 8.3440
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6095
  Variation de Stock     : -0.0008
  Stock Entrée.          : 0.0001
  Stock Sortie.          : -0.0007
  Production             : 2.6087
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 23 JANVIER 2026 (Terminé)

====================================================================================================
  📊 RÉSUMÉ ANNUEL 2026 - Ester
====================================================================================================
Mois         Jours    Prod Total      Prod Moy        oee Moy      oee Cumul
----------------------------------------------------------------------------------------------------
January      29       182.41          6.29            66.2        % 66.2        %
February     26       188.52          7.25            76.3        % 76.3        %
March        28       210.44          7.52            79.1        % 79.1        %
April        30       246.96          8.23            86.7        % 86.7        %
May          31       261.33          8.43            88.7        % 88.7        %
June         30       251.48          8.38            88.2        % 88.2        %
July         3        13.05           4.35            45.8        % 45.8        %
====================================================================================================

In [196]:
dashboard.plot_histogramme_annee_complet(annea=2026, nom_produit='Ester', std=2)

____________________________________________________________
BILAN JOURNALIER - 01 JANVIER 2026 (Terminé)
Période : du 01/01/2026 à 02:00 au 02/01/2026 à 01:30
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2673
  Variation de Stock     : -4.1001
  Stock Entrée.          : 3.0225
  Stock Sortie.          : -1.0776
  Production             : 4.1672
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5713
  Variation de Stock     : -0.0014
  Stock Entrée.          : 0.0015
  Stock Sortie.          : 0.0001
  Production             : 2.5700
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 02 JANVIER 2026 (Terminé)
Période : du 02/01/2026 à 02:15 au 03/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2920
  Variation de Stock     : -2.3258
  Stock Entrée.          : 2.9613
  Stock Sortie.          : 0.6355
  Production             : 5.9662
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7174
  Variation de Stock     : -0.0002
  Stock Entrée.          : 0.0001
  Stock Sortie.          : -0.0001
  Production             : 1.7172
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 03 JANVIER 2026 (Terminé)
Période : du 03/01/2026 à 02:00 au 04/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2965
  Variation de Stock     : -0.1118
  Stock Entrée.          : 0.6355
  Stock Sortie.          : 0.5237
  Production             : 8.1846
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5925
  Variation de Stock     : 0.0040
  Stock Entrée.          : -0.0001
  Stock Sortie.          : 0.0039
  Production             : 2.5966
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 04 JANVIER 2026 (Terminé)
Période : du 04/01/2026 à 02:00 au 05/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4864
  Variation de Stock     : -2.5205
  Stock Entrée.          : 0.5237
  Stock Sortie.          : -1.9969
  Production             : 2.9658
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6091
  Variation de Stock     : -0.0038
  Stock Entrée.          : 0.0039
  Stock Sortie.          : 0.0000
  Production             : 2.6052
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 05 JANVIER 2026 (Terminé)
Période : du 05/01/2026 à 02:00 au 06/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1836
  Variation de Stock     : 3.1964
  Stock Entrée.          : -1.9969
  Stock Sortie.          : 1.1995
  Production             : 11.3800
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7774
  Variation de Stock     : 0.0059
  Stock Entrée.          : 0.0000
  Stock Sortie.          : 0.0059
  Production             : 1.7833
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 06 JANVIER 2026 (Terminé)
Période : du 06/01/2026 à 02:00 au 07/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1141
  Variation de Stock     : 0.0033
  Stock Entrée.          : 1.1995
  Stock Sortie.          : 1.2029
  Production             : 8.1175
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6241
  Variation de Stock     : -0.0058
  Stock Entrée.          : 0.0059
  Stock Sortie.          : 0.0002
  Production             : 2.6184
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 07 JANVIER 2026 (Terminé)
Période : du 07/01/2026 à 02:00 au 08/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4959
  Variation de Stock     : 2.8446
  Stock Entrée.          : 1.2029
  Stock Sortie.          : 4.0475
  Production             : 8.3405
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5645
  Variation de Stock     : -0.0058
  Stock Entrée.          : 0.0002
  Stock Sortie.          : -0.0057
  Production             : 2.5587
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 08 JANVIER 2026 (Terminé)
Période : du 08/01/2026 à 02:00 au 09/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2796
  Variation de Stock     : -0.0404
  Stock Entrée.          : 4.0475
  Stock Sortie.          : 4.0070
  Production             : 8.2392
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5061
  Variation de Stock     : 0.0053
  Stock Entrée.          : -0.0057
  Stock Sortie.          : -0.0004
  Production             : 2.5114
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 09 JANVIER 2026 (Terminé)
Période : du 09/01/2026 à 02:00 au 10/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2916
  Variation de Stock     : -8.4586
  Stock Entrée.          : 4.0070
  Stock Sortie.          : -4.4516
  Production             : -0.1671
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : -0.0049
  Stock Entrée.          : -0.0004
  Stock Sortie.          : -0.0052
  Production             : -0.0049
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 10 JANVIER 2026 (Terminé)
Période : du 10/01/2026 à 02:00 au 11/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7454
  Variation de Stock     : 2.5854
  Stock Entrée.          : -4.4516
  Stock Sortie.          : -1.8662
  Production             : 5.3308
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.6589
  Variation de Stock     : 0.0009
  Stock Entrée.          : -0.0052
  Stock Sortie.          : -0.0044
  Production             : 1.6597
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 11 JANVIER 2026 (Terminé)
Période : du 11/01/2026 à 02:00 au 12/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.4907
  Variation de Stock     : 3.2070
  Stock Entrée.          : -1.8662
  Stock Sortie.          : 1.3408
  Production             : 8.6978
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5229
  Variation de Stock     : -0.0035
  Stock Entrée.          : -0.0044
  Stock Sortie.          : -0.0079
  Production             : 2.5194
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 12 JANVIER 2026 (Terminé)
Période : du 12/01/2026 à 02:00 au 13/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.2355
  Variation de Stock     : 0.1887
  Stock Entrée.          : 1.3408
  Stock Sortie.          : 1.5295
  Production             : 8.4242
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5168
  Variation de Stock     : 0.0143
  Stock Entrée.          : -0.0079
  Stock Sortie.          : 0.0064
  Production             : 2.5311
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 13 JANVIER 2026 (Terminé)
Période : du 13/01/2026 à 02:00 au 14/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.3149
  Variation de Stock     : -2.8835
  Stock Entrée.          : 1.5295
  Stock Sortie.          : -1.3539
  Production             : 5.4314
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.6902
  Variation de Stock     : -0.0013
  Stock Entrée.          : 0.0064
  Stock Sortie.          : 0.0051
  Production             : 1.6889
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 14 JANVIER 2026 (Terminé)
Période : du 14/01/2026 à 02:00 au 15/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.5387
  Variation de Stock     : -2.7158
  Stock Entrée.          : -1.3539
  Stock Sortie.          : -4.0697
  Production             : 2.8229
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8411
  Variation de Stock     : -0.0034
  Stock Entrée.          : 0.0051
  Stock Sortie.          : 0.0016
  Production             : 0.8377
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 15 JANVIER 2026 (Terminé)
Période : du 15/01/2026 à 02:00 au 16/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7805
  Variation de Stock     : 0.0817
  Stock Entrée.          : -4.0697
  Stock Sortie.          : -3.9880
  Production             : 2.8622
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8401
  Variation de Stock     : -0.0131
  Stock Entrée.          : 0.0016
  Stock Sortie.          : -0.0115
  Production             : 0.8270
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 16 JANVIER 2026 (Terminé)
Période : du 16/01/2026 à 02:00 au 17/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : 3.2430
  Stock Entrée.          : -3.9880
  Stock Sortie.          : -0.7451
  Production             : 3.2430
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.8803
  Variation de Stock     : 0.0000
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0115
  Production             : 0.8803
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 17 JANVIER 2026 (Terminé)
Période : du 17/01/2026 à 02:00 au 18/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 2.7582
  Variation de Stock     : -2.8270
  Stock Entrée.          : -0.7451
  Stock Sortie.          : -3.5720
  Production             : -0.0688
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : -0.0000
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0115
  Production             : -0.0000
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 18 JANVIER 2026 (Terminé)
Période : du 18/01/2026 à 02:00 au 19/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 0.0000
  Variation de Stock     : 2.6825
  Stock Entrée.          : -3.5720
  Stock Sortie.          : -0.8896
  Production             : 2.6825
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 0.7642
  Variation de Stock     : 0.0082
  Stock Entrée.          : -0.0115
  Stock Sortie.          : -0.0033
  Production             : 0.7725
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 19 JANVIER 2026 (Terminé)
Période : du 19/01/2026 à 02:00 au 20/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 5.5609
  Variation de Stock     : 2.4241
  Stock Entrée.          : -0.8896
  Stock Sortie.          : 1.5345
  Production             : 7.9850
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.4981
  Variation de Stock     : 0.0085
  Stock Entrée.          : -0.0033
  Stock Sortie.          : 0.0052
  Production             : 2.5066
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 20 JANVIER 2026 (Terminé)
Période : du 20/01/2026 à 02:00 au 21/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.3286
  Variation de Stock     : 0.2556
  Stock Entrée.          : 1.5345
  Stock Sortie.          : 1.7901
  Production             : 8.5841
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.5387
  Variation de Stock     : -0.0044
  Stock Entrée.          : 0.0052
  Stock Sortie.          : 0.0008
  Production             : 2.5343
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 21 JANVIER 2026 (Terminé)
Période : du 21/01/2026 à 02:00 au 22/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.4193
  Variation de Stock     : -2.6049
  Stock Entrée.          : 1.7901
  Stock Sortie.          : -0.8148
  Production             : 5.8144
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 1.7187
  Variation de Stock     : -0.0007
  Stock Entrée.          : 0.0008
  Stock Sortie.          : 0.0001
  Production             : 1.7180
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 22 JANVIER 2026 (Terminé)
Période : du 22/01/2026 à 02:00 au 23/01/2026 à 02:00
____________________________________________________________
PRODUIT : ESTER
------------------------------------------------------------
  Consommation (Ester)   : 8.1157
  Variation de Stock     : 0.2284
  Stock Entrée.          : -0.8148
  Stock Sortie.          : -0.5865
  Production             : 8.3440
____________________________________________________________
PRODUIT : RETINOL
------------------------------------------------------------
  Consommation (Ester)   : 2.6095
  Variation de Stock     : -0.0008
  Stock Entrée.          : 0.0001
  Stock Sortie.          : -0.0007
  Production             : 2.6087
____________________________________________________________
____________________________________________________________
____________________________________________________________
BILAN JOURNALIER - 23 JANVIER 2026 (Terminé)

==========================================================================================
  📊 RÉSUMÉ ANNUEL 2026 - Ester
==========================================================================================
Nombre de jours avec données:       177/365
Production totale année:            1354.20
Production moyenne (jours actifs):  7.65
Production min/max:                 0.03 / 14.13
Écart-type:                         2.93

🎯 RATIO oee:
  CMJ (Cible Journalière):            9.50
  oee Moyen (par jour):               80.5%
  oee Cumulé à date (fin d'année):    39.1%
  Jours > 100% (surproduction):       40 / 177
==========================================================================================

In [197]:
processor.plot_simple_tag('Hexane')